---
# == Work Dir for replicated log
- name: create work dir
  file: path={{ mesos_work_dir }} state=directory

# == Remove default configs
- name: Remove Default Mesos Configs
  file: state=absent path=/etc/mesos/

- name: Remove Mesos ZK File
  file: state=absent path=/etc/mesos/zk

- name: Remove Default Mesos-Master Config
  file: state=absent path=/etc/mesos-master/

- name: Remove Default Mesos-Slave Config
  file: state=absent path=/etc/mesos-slave/

# == Configure and recreate
- name: Mesos default config file
  template: src=conf-mesos.j2 dest=/etc/default/mesos
  notify:
    - Restart mesos-master
    - Restart mesos-slave
    - Cleanup meta/slaves/latest

- name: Mesos Master config file
  template: src=conf-mesos-master.j2 dest=/etc/default/mesos-master
  when: mesos_install_mode == "master"
  notify:
    - Restart mesos-master

- name: Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave
  when: mesos_install_mode == "slave"
  notify:
    - Restart mesos-slave
    - Cleanup meta/slaves/latest

- name: Check if systemd exists
  stat: path=/lib/systemd/system/
  register: systemd_check

- name: Mesos slave stop zookeeper
  service: name=zookeeper state=stopped
  when: mesos_install_mode == "slave" and systemd_check.stat.exists == true

- name: Mesos slave stop zookeeper
  service: name=zookeeper state=started
  when: mesos_install_mode == "master" and systemd_check.stat.exists == true

- name: Enable/Disable mesos-master service
  service: name=mesos-master enabled="{{ (mesos_install_mode == 'slave') | ternary('no', 'yes') }}"
  when: systemd_check.stat.exists == true

- name: Enable/Disable mesos-slave service
  service: name=mesos-slave enabled="{{ (mesos_install_mode == 'master') | ternary('no', 'yes') }}"
  when: systemd_check.stat.exists == true

- name: Enable/Disable zookeeper service
  service: name=zookeeper enabled="{{ (mesos_install_mode == 'slave') | ternary('no', 'yes') }}"
  when: systemd_check.stat.exists == true
